version: "3.0"

services:
  app:
    image: 'moviedb:latest'
    build:
      context: .
    container_name: moviedb
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/moviedb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=spider1998
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:14-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=spider1998