CREATE TABLE Addresses
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    street   VARCHAR(100) NOT NULL,
    city     VARCHAR(50)  NOT NULL,
    country  VARCHAR(50)  NOT NULL,
    zip_code VARCHAR(5)   NOT NULL
);
CREATE TABLE Dates_Audit
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);
CREATE TABLE Roles
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(25) NOT NULL
);
CREATE TABLE Users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(30) NOT NULL UNIQUE,
    password      VARCHAR     NOT NULL,
    first_name    VARCHAR(50),
    last_name     VARCHAR(50),
    age           INT CHECK (age > 17 and age < 126),
    email         VARCHAR(65),
    phone_number  VARCHAR(25),
    address_id    BIGINT REFERENCES Addresses (id),
    date_audit_id BIGINT REFERENCES Dates_Audit (id),
    role_id       BIGINT REFERENCES Roles (id)
);

CREATE TABLE Directors
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name  VARCHAR(50) NOT NULL,
    age        INT CHECK (age > 17 and age < 126)
);
CREATE TABLE Actors
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name  VARCHAR(50) NOT NULL,
    age        INT CHECK (age > 17 and age < 126)
);
CREATE TABLE Movies
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR(100) NOT NULL,
    release_date DATE         NOT NULL,
    director_id  BIGINT REFERENCES Directors (id)
);
CREATE TABLE Movie_Actor
(
    movie_id BIGINT REFERENCES Movies (id),
    actor_id BIGINT REFERENCES Actors (id),
    PRIMARY KEY (actor_id, movie_id)
);

CREATE TABLE User_Movie
(
    user_id  BIGINT REFERENCES Users (id),
    movie_id BIGINT REFERENCES Movies (id),
    PRIMARY KEY (movie_id, user_id)
);

INSERT INTO Roles(role_name)
VALUES ('ROLE_ADMIN');
INSERT INTO Roles(role_name)
VALUES ('ROLE_USER');
INSERT INTO Users(username, password, role_id)
VALUES ('testadmin', '$2a$10$gHBXJ7VbwZcHFY8Bpdyh.eFwmEASW3dy8uzK6ylQ/e3E1ewoB0Fnq', 1);
INSERT INTO Addresses(street, city, country, zip_code)
VALUES ('Teststreet', 'Testcity', 'Testcountry', '44444');
INSERT INTO Dates_Audit(created_at, updated_at)
VALUES ('2022-09-06 13:32:58.341000', '2022-09-06 13:32:58.341000');
INSERT INTO Users(username,
                  password,
                  first_name,
                  last_name,
                  age,
                  email,
                  phone_number,
                  address_id,
                  date_audit_id,
                  role_id)
VALUES          ('testusername1',
                 '$2a$10$ecot2OQgYO1VSwXRkreK/eudEYgOy0nFsrk5pr.pAo18V6JXx9W8G',
                 'Testfirstname',
                 'Testlastname',
                 24,
                 'test2021@gmail.com',
                 '+380 99 200 20 90',
                 1,
                 1,
                 2);
INSERT INTO Addresses(street, city, country, zip_code)
VALUES ('Teststreet', 'Testcity', 'Testcountry', '44444');
INSERT INTO Dates_Audit(created_at, updated_at)
VALUES ('2022-09-06 13:32:58.341000', '2022-09-06 13:32:58.341000');
INSERT INTO Users(username,
                  password,
                  first_name,
                  last_name,
                  age,
                  email,
                  phone_number,
                  address_id,
                  date_audit_id,
                  role_id)
VALUES          ('testusername2',
                 '$2a$10$ecot2OQgYO1VSwXRkreK/eudEYgOy0nFsrk5pr.pAo18V6JXx9W8G',
                 'Testfirstname',
                 'Testlastname',
                 24,
                 'test2023@gmail.com',
                 '+380 99 200 20 90',
                 2,
                 2,
                 2);
INSERT INTO Directors(first_name, last_name, age) VALUES ('Testname', 'Testlastname', 54);
INSERT INTO Actors(first_name, last_name, age) VALUES ('Testname', 'Testlastname', 34);
INSERT INTO Movies(title, release_date, director_id) VALUES ('testmovie1', '2022-02-20', 1);
INSERT INTO Movie_Actor(movie_id, actor_id) VALUES (1, 1);